// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHT5s_ml2aHVms5OanyQd4pamGHb2UnvM',
    appId: '1:899564513816:web:51f92f93af03d3f9c0716d',
    messagingSenderId: '899564513816',
    projectId: 'cuoiki2-58fc1',
    authDomain: 'cuoiki2-58fc1.firebaseapp.com',
    storageBucket: 'cuoiki2-58fc1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXay0bzjZAp3ClrWcR3fIstfKTYZ89w08',
    appId: '1:899564513816:android:8bbdb42c73be59e6c0716d',
    messagingSenderId: '899564513816',
    projectId: 'cuoiki2-58fc1',
    storageBucket: 'cuoiki2-58fc1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVhekHuEocQy2Md4INQyhMBobOxm1E1Pk',
    appId: '1:899564513816:ios:3730f51b13f435efc0716d',
    messagingSenderId: '899564513816',
    projectId: 'cuoiki2-58fc1',
    storageBucket: 'cuoiki2-58fc1.appspot.com',
    iosBundleId: 'com.example.cuoiki',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVhekHuEocQy2Md4INQyhMBobOxm1E1Pk',
    appId: '1:899564513816:ios:d2fe022c9b359174c0716d',
    messagingSenderId: '899564513816',
    projectId: 'cuoiki2-58fc1',
    storageBucket: 'cuoiki2-58fc1.appspot.com',
    iosBundleId: 'com.example.cuoiki.RunnerTests',
  );
}
